# Generated by Django 3.1.5 on 2021-01-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('courses', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
